### ISSUE TITLE
This is one command script working

### ISSUE THREAD

**Issue by omar2205** [michaelshumshum/r-placer#10]
```python
import requests

AUTH_CODE = 'REDACTED'

headers = {
    'authorization': f'Bearer {AUTH_CODE}',
    'User-Agent': 'REDACTED',
}

json_data = {
    'operationName': 'setPixel',
    'variables': {
        'input': {
            'actionName': 'r/replace:set_pixel',
            'PixelMessageData': {
                'coordinate': {
                    'x': 100,
                    'y': 100,
                },
                'colorIndex': 2,
                'canvasIndex': 0,
            },
        },
    },
    'query': '''mutation setPixel($input: ActInput!) {
  act(input: $input) {
    data {
      ... on BasicMessage {
        id
        data {
          ... on GetUserCooldownResponseMessageData {
            nextAvailablePixelTimestamp
            __typename
          }
          ... on SetPixelResponseMessageData {
            timestamp
            __typename
          }
          __typename
        }
        __typename
      }
      __typename
    }
    __typename
  }
}
''',
}

response = requests.post('https://gql-realtime-2.reddit.com/query', headers=headers, json=json_data)

```

I'm guessing we just need to figure out, how to refresh the auth token?

**Comment by omar2205** [comment]
So, figure it out using a dev app.

But, that won't work with created accounts. You need to make an app script and get the client_id and client_secret.

**Comment by wael9999** [comment]
any updates

**Comment by omar2205** [comment]
This is working https://github.com/rdeepak2002/reddit-place-script-2022

**Comment by michaelshumshum** [comment]
> This is working https://github.com/rdeepak2002/reddit-place-script-2022

i guess one approach we could do is add the accounts to the developer list. i would imagine it not to be too hard to programmatically do that.

**Comment by omar2205** [comment]
That was what I was thinking, create the main app, and when you create an account, add it to the developers.

**Comment by omar2205** [comment]
But, as you saw, we just need a valid auth token and post one query.

**Comment by omar2205** [comment]
@michaelshumshum can you enable discussions?
& Verifying accounts mail drops the timeout to 5mins (new accounts get 10-20mins timeouts)
Is there a way?

**Comment by michaelshumshum** [comment]
https://github.com/michaelshumshum/r-placer/discussions/11

maybe we try verifying the emails? verify the email of some new account and see if it turns to 5 minutes. otherwise, it should be based on karma, which makes it impossible.

**Comment by michaelshumshum** [comment]
discussion moved to `discussions`
