### ISSUE TITLE
Hey i dont know

### ISSUE THREAD

**Issue by 2006lou** [michaelshumshum/r-placer#12]
Im 1000% new to those things and im just trying to get bot to defends a flag on the maps and i get this error when i try to run it 
![image](https://user-images.githubusercontent.com/59489193/161390957-9029cabe-f26e-4406-9bd6-8e82ae62d401.png)

**Comment by michaelshumshum** [comment]
the bot doesn't work right now. i am not sure if anybody has a complete bot working right now. some people have made some achievements, but in no way have created a full bot array.

**Comment by michaelshumshum** [comment]
issue is irrelevant now
