### ISSUE TITLE
bots get autobanned without even interacting with r/place

### ISSUE THREAD

**Issue by michaelshumshum** [michaelshumshum/r-placer#13]
may need to look into new method of mass account creation

**Comment by lexuv2** [comment]
i don't think that those accounts get banned, when logging to them manually i can still place tiles

**Comment by michaelshumshum** [comment]
the ban method that they are using is just extending your cooldown to 15 years. all my accounts are stuck like that. though, i noticed that the limitation goes away after 1 day.

**Comment by michaelshumshum** [comment]
solution is to have the account join a random subreddit before using r/place. not a single account banned for me since.
