### ISSUE TITLE
Can you explain how to do it a bit more simply

### ISSUE THREAD

**Issue by BingoBongos12** [michaelshumshum/r-placer#17]
#help wanted#
Hey I've been trying for hours to get a place on the map and can't manage to actually put something down and have found out you can really only use bots so I was wondering if you could help me set this up

**Comment by michaelshumshum** [comment]
- make all the accounts.
- create a new file in the folder called `accounts.csv`, which is like an excel document. 
- for every account, make a new row with info of your account, like this `email username password`. email is optional, so just put some random info there. it was just for me.
- get your image. 
- run the script like this `python main.py your_image x-coordinate y-coordinate`. 
- first time setup for all your accounts will be done automatically.

**Comment by michaelshumshum** [comment]
place has ended already
