### ISSUE TITLE
im lost on this one [Errno 2] No such file or directory: 'config.json'

### ISSUE THREAD

**Issue by alex7346** [michaelshumshum/r-placer#19]
this is the error i got on account_maker

FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
PS C:\Users\myuser> & C:/Users/myuser/AppData/Local/Microsoft/WindowsApps/python3.11.exe c:/Users/myuser/OneDrive/Desktop/r-placer-master/account_maker.py
Traceback (most recent call last):
  File "c:\Users\myuser\OneDrive\Desktop\r-placer-master\account_maker.py", line 5, in <module>
    import _config
  File "c:\Users\myuser\OneDrive\Desktop\r-placer-master\_config.py", line 3, in <module>
    with open('config.json', 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

**Comment by oOHiyoriOo** [comment]
the config.json is missing.
get it again from the repository here.
