### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 0)

### ISSUE THREAD

**Issue by LookItsAndy** [michaelshumshum/r-placer#21]
im trying to run main.py but I'm getting this error message and I don't know why

Traceback (most recent call last):
  File "D:\user\Documents\GitHub\r-placer\main.py", line 12, in <module>
    m = management.manager(image_dir, image_location)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\user\Documents\GitHub\r-placer\management.py", line 85, in __init__
    email, username, password = row
    ^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 3, got 0)

**Comment by michaelshumshum** [comment]
you need an `accounts.csv` file that contains all your accounts. read the README.
