### ISSUE TITLE
Authorization failed

### ISSUE THREAD

**Issue by Davidkaa01** [michaelshumshum/r-placer#25]
i put the correct username and password but this is what i get
response: 400 - {"reason": "INCORRECT_USERNAME_PASSWORD", "code": 400, "explanation": "incorrect username or password"}

**Comment by michaelshumshum** [comment]
what part is this? the `accounts.csv` or `config.json`?

**Comment by Davidkaa01** [comment]
i put the username and password in the config.json, started it in powershell and got that message

this is the config.json
{
    "image_path": "image.jpg",
    "image_start_coords": [866, 241],
    "legacy_transparency": true,
    "thread_delay": 2,
    "unverified_place_frequency": false,
    "compact_logging": true,
    "using_tor": false,
    "tor_ip": "127.0.0.1",
    "tor_port": 1881,
    "tor_control_port": 9051,
    "tor_password": "Passwort",
    "tor_delay": 5,
    "use_builtin_tor": true,
    "workers": {
        "username": {
            "password": "password",
            "start_coords": [0, 0]
        }
    }
}

**Comment by michaelshumshum** [comment]
where did you get this from? it's not even mine.

```
{
  "account-maker-email": "morganchristansen98@protonmail.com",
  "verbose": true,
  "event-update-interval": 30,
  "worker-count": 12,
  "tor": false,
  "apps": [
    {
      "client-id": "9GjDA0K8MzQpgnSygLxb7A",
      "secret": "Iv6CbrI-2N1wOPdTQurYUcO06TSjJg"
    },
    {
      "client-id": "zDd-IrVMQS_aYofDTdKpSA",
      "secret": "6xgDrQn66I9F3rLYoOPpED4XGHLvkA"
    },
    {
      "client-id": "K8Eth9i_qQ5zbtXDI9Em7w",
      "secret": "baaqWQ8REjC9LKLqY_ULojr7gh--7g"
    }
  ],
  "main-dev-account": {
    "username": "xebMnVWIdoxjReEZepoU",
    "password": "@P8xlIrB-zz0PmaB"
  }
}
```
this is what it should look like. i can't help you if all you needed to do was read instructions.

**Comment by Davidkaa01** [comment]
but this is what i downloaded

**Comment by michaelshumshum** [comment]
downloaded from where? you are in the wrong repo.

`https://github.com/rdeepak2002/reddit-place-script-2022/`
that's where you need to be.
