### ISSUE TITLE
Why do you complicate things with google sheets?

### ISSUE THREAD

**Issue by omar2205** [michaelshumshum/r-placer#3]
why not drop the accounts into a .txt file?

**Comment by michaelshumshum** [comment]
idk. in the future, when you get hundreds of accounts, putting them into a CSV is preffered, at least for me. if you put it into a text file, you would have to deal with string parsing a little bit.

**Comment by michaelshumshum** [comment]
there is also the issue with opening files on the drive directly. either you leave it open for the entire time your script runs or open it every time you edit it. the first is that if there were any problems that caused the script to stop, the text would not save. the latter is that it takes more time to open files. an API request is relatively faster and safer.

**Comment by omar2205** [comment]
Okay
