### ISSUE TITLE
Do you guys have some sort of todo list for this?

### ISSUE THREAD

**Issue by Joshument** [michaelshumshum/r-placer#5]
Interested in contributing as /pol/ fucked over a trans flag (presumably with either bots or mass alts) and I'd like to get back at them

**Comment by michaelshumshum** [comment]
first order of business is to fix the authorization issue. i have found the theoretical method to write pixels, but something is weird about the authorization. 

once that is solved, making the script more suitable for lots of simultaneous bot accounts is next. then it would be to make the whole script user friendly.

for now, our goal is to just writ a pixel to the screen. i am not sure if anybody has done that yet.

**Comment by michaelshumshum** [comment]
most of the things on this "to do list" are kinda finished.
